import { afterEach, expect, test, vi } from 'vitest'
import { waitFor } from '@solidjs/testing-library'
const ipc = vi.hoisted(() => ({ selectCloudImport: vi.fn(), finishCloudImport: vi.fn(), beginCloudImport: vi.fn(), cancelCloudImport: vi.fn().mockResolvedValue(undefined), listTasks: vi.fn().mockResolvedValue([]) }))
const ui = vi.hoisted(() => ({ selectedTaskId: vi.fn(() => 'elsewhere'), setSelectedTaskId: vi.fn(), setSelectedSessionIdForTask: vi.fn() }))
vi.mock('../lib/ipc', () => ipc)
vi.mock('./ui', () => ui)
vi.mock('./sessions', () => ({ setSessions: vi.fn(), sessionsForTask: () => [], cleanupSessionStorage: vi.fn(), clearSessionContextsForTask: vi.fn() }))
import { startCloudTaskImport, retryCloudTaskImport, tasks, setTasks, isTaskCreating, getTaskError, getCloudTaskPhase, loadTasks, removePlaceholderTask } from './tasks'
const choice = { index: 2, title: 'Notifications', updated: '1d ago' }
const result = { task: { id: 'real', projectId: 'project', name: 'Notifications' }, session: { id: 'session' } }
afterEach(() => { for (const task of [...tasks]) removePlaceholderTask(task.id); setTasks([]); vi.clearAllMocks() })
test('import creates a named placeholder, survives reload, and finishes without stealing focus', async () => {
  let resolve!: () => void
  ipc.selectCloudImport.mockReturnValue(new Promise<void>(r => { resolve = r }))
  ipc.finishCloudImport.mockResolvedValue(result)
  const id = startCloudTaskImport('project', 'import', choice)
  expect(tasks[0].name).toBe('Notifications')
  expect(isTaskCreating(id)).toBe(true)
  expect(getCloudTaskPhase(id)).toBe('Importing…')
  await loadTasks('project')
  expect(tasks.some(t => t.id === id)).toBe(true)
  resolve()
  await waitFor(() => expect(tasks[0].id).toBe('real'))
  expect(ui.setSelectedTaskId).not.toHaveBeenCalled()
})
test('finalization retry reuses the imported conversation and ignores repeated clicks', async () => {
  ipc.selectCloudImport.mockResolvedValue(undefined)
  ipc.finishCloudImport.mockRejectedValueOnce(new Error('Disk full')).mockResolvedValueOnce(result)
  const id = startCloudTaskImport('project', 'retry', choice)
  await waitFor(() => expect(getTaskError(id)).toContain('Disk full'))
  retryCloudTaskImport(id); retryCloudTaskImport(id)
  await waitFor(() => expect(tasks[0].id).toBe('real'))
  expect(ipc.selectCloudImport).toHaveBeenCalledTimes(1)
  expect(ipc.finishCloudImport).toHaveBeenCalledTimes(2)
})
test('selection retry refreshes the picker and finds the title rather than reusing its old ordinal', async () => {
  ipc.selectCloudImport.mockRejectedValueOnce(new Error('CLI exited')).mockResolvedValueOnce(undefined)
  ipc.finishCloudImport.mockResolvedValue(result)
  ipc.beginCloudImport.mockResolvedValue({ importId: 'fresh', sessions: [{ ...choice, index: 1 }] })
  const id = startCloudTaskImport('project', 'stale', choice)
  await waitFor(() => expect(getTaskError(id)).toContain('CLI exited'))
  retryCloudTaskImport(id)
  await waitFor(() => expect(tasks[0].id).toBe('real'))
  expect(ipc.selectCloudImport).toHaveBeenLastCalledWith('project', 'fresh', 1)
  expect(ipc.cancelCloudImport).toHaveBeenCalledWith('stale')
})
test('removing a failed import releases its prepared checkout', async () => {
  ipc.selectCloudImport.mockResolvedValue(undefined)
  ipc.finishCloudImport.mockRejectedValueOnce(new Error('Disk full'))
  const id = startCloudTaskImport('project', 'discard', choice)
  await waitFor(() => expect(getTaskError(id)).toContain('Disk full'))
  removePlaceholderTask(id)
  expect(ipc.cancelCloudImport).toHaveBeenCalledWith('discard')
  expect(tasks.some(t => t.id === id)).toBe(false)
  expect(getCloudTaskPhase(id)).toBeNull()
})
test('retry refuses ambiguous titles instead of importing a different session', async () => {
  ipc.selectCloudImport.mockRejectedValueOnce(new Error('CLI exited'))
  ipc.beginCloudImport.mockResolvedValue({ importId: 'ambiguous', sessions: [choice, { ...choice, index: 3 }] })
  const id = startCloudTaskImport('project', 'old', choice)
  await waitFor(() => expect(getTaskError(id)).toContain('CLI exited'))
  retryCloudTaskImport(id)
  await waitFor(() => expect(getTaskError(id)).toContain('duplicate title'))
  expect(ipc.selectCloudImport).toHaveBeenCalledTimes(1)
  expect(ipc.cancelCloudImport).toHaveBeenCalledWith('ambiguous')
})
